name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm steps
      run: |
        npm install
        npm run abaplint
        npm run merge
        npm run merge.ci
    - name: deploy-merged-build
      if: github.ref == 'refs/heads/main' && github.repository == 'pawelwiejkut/bw_trfn_tester'
      env:
        GITHUB_API_KEY: ${{ secrets.MY_TOKEN }}
      run: ./ci/deploy-merged-build.sh
    - name: deploy-release-tag
      if: github.ref == 'refs/heads/main' && github.repository == 'pawelwiejkut/bw_trfn_tester'
      env:
        GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: ./ci/deploy-release-tag.sh
    - name: Upload build artifact
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: zabapgit_standalone.abap
        path: ./zabapgit.abap
        retention-days: 7
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@main
      # GITHUB_TOKEN in forked repositories is read-only
      # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
      if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}       
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
